spring:
  application:
    name: mgw
  datasource:
    url: jdbc:mysql://localhost:3306/mgw
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true # 1-indexed

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
