spring:
  application:
    name: mgw
  datasource:
    url: jdbc:mysql://localhost:3306/mgw
    username: root
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true # 1-indexed

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000